### ISSUE TITLE
Add cUrl to libraries to support Docker HEALTHCHECK

### ISSUE THREAD

**Issue by jason-fox** [smartsdk/ngsi-timeseries-api#167]
I was thinking of adding a `HEALTHCHECK` to my QuantumLeap instance as shown:

```yaml
  quantumleap:
    image: smartsdk/quantumleap:0.5.1
    hostname: quantumleap
    container_name: fiware-quantumleap
    ports:
      - "8668:8668"
    depends_on:
      - cratedb
    environment:
      - CRATE_HOST=cratedb
    healthcheck:
      test: curl --fail -s http://localhost:8668/v2/version || exit 1
```

However, the current `Dockerfile` based on alpine doesn't include cUrl.

Should

```Dockerfile
RUN apk add --no-cache curl
```

be added to the libraries list in the Dockerfile at [line 3](https://github.com/smartsdk/ngsi-timeseries-api/blob/a18d826217ca9daf237907de8a5475dc7607dda4/Dockerfile#L3)?
