### ISSUE TITLE
404 Error when subscribing to a entity from Orion

### ISSUE THREAD

**Issue by dSalvoG** [smartsdk/ngsi-timeseries-api#331]
Hello, the **context of the bug** is as follows:

- I'm working on an example to get a series of data using Fiware.

- When I try to subscribe an entity using Orion's APIs (http://localhost:1026/v2/subscriptions/):

**Request: **

- I would like to know how can I configure the docker image to get Quantum Leap service running and making subscription into my Orion entity.

[*] Content-type : application/json
[*] fiware-service : openiot
[*] fiware-servicepath : /

```
{
  "description": "Notify QuantumLeap of all Urban Acoustic Classification Nodes",
  "subject": {
    "entities": [
      {
        "idPattern":"urn:ngsi-ld:AcousticNode.*"
      }
    ],
    "condition": {"attrs": ["modDate"] }
  },
  "notification": {
    "http": {
      "url": "http://localhost:8668/v2/notify"
    },
    "attrs": [
      "noiseClass"
    ],
    "metadata": ["dateCreated", "dateModified"]
  },
  "throttling": 1
}
```

**I get this response, when I check the subscription in Orion (http://{{orion}}/v2/subscriptions/)**

[*] fiware-service : openiot
[*] fiware-servicepath : /

```
{
        "id": "5ef73d5e55bc665064900c18",
        "description": "Notify QuantumLeap of all Urban Acoustic Classification Nodes",
        "status": "failed",
        "subject": {
            "entities": [
                {
                    "idPattern": "urn:ngsi-ld:AcousticNode.*"
                }
            ],
            "condition": {
                "attrs": [
                    "modDate"
                ]
            }
        },
        "notification": {
            "timesSent": 1,
            "lastNotification": "2020-06-27T12:36:46.00Z",
            "attrs": [
                "noiseClass"
            ],
            "attrsFormat": "normalized",
            "http": {
                "url": "http://localhost:8668/v2/notify"
            },
            "metadata": [
                "dateCreated",
                "dateModified"
            ],
            "lastFailure": "2020-06-27T12:36:46.00Z"
        },
        "throttling": 1
    }
```

**My docker-compose.yml file**

```
version: '3'

services:

  orion:
    image: fiware/orion:1.13.0
    ports:
      - "1026:1026"
    command: -logLevel DEBUG -noCache -dbhost mongo
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:1026/version"]
      interval: 1m
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  quantumleap:
    image: smartsdk/quantumleap
    ports:
      - "8668:8668"
    depends_on:
      - mongo
      - orion
      - crate
    environment:
      - CRATE_HOST=crate

  crate:
    image: crate:1.0.5
    ports:
      # Admin UI
      - "4200:4200"
      # Transport protocol
      - "4300:4300"
    command: -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
    volumes:
      - cratedata:/data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=crate-datasource,grafana-clock-panel,grafana-worldmap-panel
    depends_on:
      - crate

volumes:
  mongodata:
  cratedata:
  redisdata:

networks:
  quantum_net:
```

**Entity Creation File**

```
import json
import datetime
 
currentDT = datetime.datetime.now()
print (str(currentDT))

data = {
	"type": "Device",
	
	"id": "urn:ngsi-ld:AcousticNode:100",
	
	"source": {
	    "type":"URL",
	    "value":"xxxx"
	},
	
	"dataProvider": {
	    "type":"URL",
	    "value":"xxxx"
	},
	
	"category": {
	    "type": "Text",
	    "value": "sensor"
	},
	
	"controlledProperty": {
	    "type": "Text",
	    "value": "noiseClass"
	},
	
	"noiseClass": {
		"type": "Property",
		"value": "Unknown"
	},
	
	"airConditioner":{
		"type": "Property",
		"value": "Unknown"
    },

    "carHorn": {
    	"type": "Property",
    	"value": "Unknown"
    },

    "childrenPlaying":{
    	"type": "Property",
    	"value": "Unknown"
    },

    "dogBark": {
    	"type": "Property",
    	"value": "Unknown"
    },

    "Drilling": {
    	"type": "Property",
    	"value": "Unknown"
    },

    "engineIdling": {
    	"type": "Property",
    	"value": "Unknown"
    },

    "gunShot": {
    	"type": "Property",
    	"value": "Unknown"
    },

    "Jackhammer": {
    	"type": "Property",
    	"value": "Unknown"
    },

    "Siren": {
    	"type": "Property",
    	"value": "Unknown"
    },

    "streetMusic": {
    	"type": "Property",
    	"value": "Unknown"
    },
	
	"function": {
	    "type": "Text",
	    "value": "sensing"
	},
	
	"name": {
	    "type":"Text",
	    "value": "Raspberry 000"
	},
	
	"address": {
	    "type": "PostalAddress",
	    "value": {
	        "streetAddress": "anon",
	        "addressRegion": "anon",
	        "addressLocality": "anon",
	        "postalCode": "xxxx"
	    },
	    
	    "metadata": {
	        "verified": {
	        	"value": "true",
	            "type": "Boolean"
	        }
	    }
	},
	"location": {
	    "type": "geo:json",
	    "value": {
	         "type": "Point",
	         "coordinates": [xxxx, -xxxx]
	    }
	},

	"creDate": {
		"type":"Text",
		"value":str(currentDT)
	},

	"modDate": {
		"type":"Text",
		"value":str(currentDT)
	}
}

## Making a POST request to Orion Broker
import requests

# defining the api-endpoint
API_ENDPOINT = "http://localhost:1026/v2/entities/"

# headers
headers_string={
    'Content-Type':'application/json',
	'fiware-service':'openiot',
    'fiware-servicepath':'/'
    }

# data to be sent to api
payload = json.dumps(data)


# request post (using json payload)
x = requests.post(url= API_ENDPOINT, data= payload, headers= headers_string,)

#print the response text (the content of the requested file):
print(x.text)
```

**For the Quantum Leap Version Request (http://localhost:8668/v2/version)**
**I get the next response: **

```
{
  "detail": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.",
  "status": 404,
  "title": "Not Found",
  "type": "about:blank"
}
```

**Thank you for your time!!**
